# Generated by Django 4.2.7 on 2024-01-08 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0004_review'),
        ('patient', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_types', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Face-to-Face', 'Face-to-Face'), ('Physical', 'Physical'), ('Teleconsultation', 'Teleconsultation'), ('Virtual', 'Virtual'), ('In-Person', 'In-Person'), ('Out-Person', 'Out-Person'), ('Other', 'Other')], max_length=50)),
                ('appointment_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running'), ('Cancelled', 'Cancelled'), ('Missed', 'Missed'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=50)),
                ('symptoms', models.TextField()),
                ('cancel', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletime')),
            ],
        ),
    ]
