# Generated by Django 4.2.7 on 2023-12-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
