# Generated by Django 4.2.7 on 2023-12-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='musicican',
            new_name='musician',
        ),
    ]
