# Generated by Django 5.0.1 on 2024-01-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_available_time_doctor_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.ManyToManyField(to='doctor.availabletime'),
        ),
    ]
